# Generated by Django 5.1.3 on 2024-11-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('nome_limpo', models.CharField(editable=False, max_length=255)),
                ('profissao', models.CharField(max_length=255)),
                ('empresa_ligada', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
