# Generated by Django 5.1.3 on 2024-11-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elite', '0002_pessoa_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='descricao',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
